name: CD

on:
  push:
    tags:
      - "*"

jobs:
  pushdocker:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: olegtarasov/get-tag@v2
        id: tag_name
      - uses: docker/build-push-action@v1
        id: buildDocker
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kaprino/kaprino
          tags: ${{ steps.tag_name.outputs.tag }},latest
          push: true
  build-win:
    runs-on: "windows-latest"

    steps:
      - uses: actions/checkout@v2
      - run: |
          git clone https://github.com/llvm/llvm-project.git --depth 1 -b release/9.x
          cd llvm-project/llvm
          mkdir build
          cd build
          cmake .. -G "MinGW Makefiles" -DLLVM_BUILD_TOOLS=OFF
          mingw32-make
          mingw32-make install
        name: Install LLVM
      - run: |
          mkdir build
          cd build
          cmake .. -G "MinGW Makefiles"
          mingw32-make
        name: Build Kaprino
      - uses: actions/upload-artifact@v2
        with:
          name: "kprc for Windows"
          path: "./build/**/*"