name: CD

on:
  push:
    tags:
      - "*"

jobs:
  pushdocker:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: olegtarasov/get-tag@v2
        id: tag_name
      - uses: docker/build-push-action@v1
        id: buildDocker
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kaprino/kaprino
          tags: ${{ steps.tag_name.outputs.tag }},latest
          push: true
  build-win:
    runs-on: "windows-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.0
      - run: |
          Invoke-WebRequest "https://github.com/llvm/llvm-project/releases/download/llvmorg-9.0.1/llvm-9.0.1.src.tar.xz" -OutFile "llvm-9.0.1.src.tar.xz"
          7z x ./llvm-9.0.1.src.tar.xz
          7z x ./llvm-9.0.1.src.tar
          cd llvm-9.0.1.src
          mkdir build
          cd build
          cmake .. -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DLLVM_BUILD_TOOLS=OFF
          msbuild ALL_BUILD.vcxproj -p:Configuration=Release
          msbuild INSTALL.vcxproj -p:Configuration=Release
        name: Install LLVM
      - run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release
          msbuild ALL_BUILD.vcxproj -p:Configuration=Release
        name: Build kprc
      - uses: actions/upload-artifact@v2
        name: Publish artifact
        with:
          name: "kprc for Windows"
          path: "./build/Release/**/*"
  build-linux:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - run: |
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-9.0.1/llvm-9.0.1.src.tar.xz
          tar xJf llvm-9.0.1.src.tar.xz
          cd llvm-9.0.1.src
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DLLVM_BUILD_TOOLS=OFF
          make
          sudo make install
        name: Install LLVM
      - run: |
          sudo apt-get install uuid uuid-dev
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make
        name: Build kprc
      - uses: actions/upload-artifact@v2
        name: Publish artifact
        with:
          name: "kprc for Ubuntu"
          path: "./build/**/*"