name: CD

on:
  push:
    tags:
      - "*"

jobs:
  pushdocker:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: olegtarasov/get-tag@v2
        id: tag_name
      - uses: docker/build-push-action@v1
        id: buildDocker
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kaprino/kaprino
          tags: ${{ steps.tag_name.outputs.tag }},latest
          push: true
  build-win:
    runs-on: "windows-latest"

    steps:
      - uses: actions/checkout@v2
      - run: ./build.ps1
        name: Build
      - uses: actions/upload-artifact@v2
        name: Publish artifact
        with:
          name: "kprc for Windows"
          path: "./build/**/*"
  build-linux:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - run: |
          apt install util-linux -y
          chmod +x ./build.sh
          ./build.sh
        name: Build
      - uses: actions/upload-artifact@v2
        name: Publish artifact
        with:
          name: "kprc for Ubuntu"
          path: "./build/**/*"