name: Release for docker

on:
  push:
    tags:
      - "*"
    branches:
      - "feature/cd*"

jobs:
  publish-image:
    name: publish docker image
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get tag or branch name
        id: source_name
        run: |
          echo ::set-output name=tag_name::${GITHUB_REF#refs/*/}
        shell: bash

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image (Test)
        if: ${{ !startsWith(steps.source_name.outputs.tag_name, 'v') }}
        uses: docker/build-push-action@v2
        with:
          tags: |
            kaprino/kaprino:test
          push: false

      - name: Build and push Docker image
        if: startsWith(steps.source_name.outputs.tag_name, 'v')
        uses: docker/build-push-action@v2
        with:
          tags: |
            kaprino/kaprino:${{ steps.source_name.outputs.tag_name }}
            kaprino/kaprino:latest
