name: MacOS release

on:
  push:
    tags:
      - "*"

jobs:
  #
  # Build the sources for Linux and publish achievements.
  #
  build-mac:
    runs-on: "macos-latest"
    #
    # Specify the version of the compilers.
    #
    env:
      CXX: g++-8
      CC: gcc-8

    steps:
      - uses: actions/checkout@v2
      #
      # Get a tag name which is used to release achievements.
      #
      - uses: olegtarasov/get-tag@v2
        id: tag_name
      #
      # Build the sources.
      #
      - run: |
          python3 bootstrap.py --config Release
        name: Build kprc
      #
      # Publish them.
      #
      - uses: actions/upload-artifact@v2
        name: Publish artifact
        with:
          name: "kprc-${{ steps.tag_name.outputs.tag }}-macos-x64"
          path: "./build/**/*"
