name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    container:
      image: kaprino/llvm:latest
      env:
        LLVM_SYS_90_PREFIX: /root/llvm-9
        PATH: $PATH:/root/.cargo/bin

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check LLVM version
        run: /root/llvm-9/llvm-config --version
      - name: Test kaprino
        run: cargo test
