name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    container:
      image: kaprino/llvm:latest

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make apt-get up-to-date
        run: apt-get update
      - name: Install libffi-dev
        run: apt-get install -y libffi-dev
      - name: Setup Rust
        run: |
          rustup install stable
          rustup default stable
      - name: Get toolchains
        run: rustup show
      - name: Test kaprino
        run: cargo test
